import React, { useEffect, useState } from "react";
import { EmojiInput, EmojiTextarea } from "../EmojiField.jsx";

const f = (key, label, type = "text") => ({ key, label, type });
const TABS = [
  ["main", "Основное", [f("player_name", "Название для игрока", "emoji"), f("system_name", "Системное название"), f("short_name", "Короткое название", "emoji"), f("admin_name", "Название в админке", "emoji"), f("inventory_name", "Название в инвентаре", "emoji"), f("market_name", "Название на рынке", "emoji"), f("bot_message_name", "Название в сообщениях бота", "emoji"), f("game_id", "Игровой ID"), f("system_id", "Системный ID"), f("legacy_id", "Старый ID"), f("legacy_aliases", "Алиасы старых ID", "list")]],
  ["descriptions", "Описания", [f("hidden_description", "Скрытое описание", "emoji_textarea"), f("hidden_description_conditions", "Условия открытия", "json"), f("hidden_description_locked_text", "Текст, если условие не выполнено", "emoji_textarea"), f("hidden_description_show_hint", "Показывать намёк", "checkbox")]],
  ["classification", "Категория и качество", [f("inventory_tab", "Вкладка инвентаря"), f("quality_color", "Цвет качества"), f("quality_cost_multiplier", "Множитель стоимости", "number"), f("quality_power_multiplier", "Множитель силы", "number"), f("quality_drop_available", "Доступно в дропе", "checkbox"), f("quality_market_available", "Доступно на рынке", "checkbox"), f("quality_craft_available", "Доступно в ремесле", "checkbox"), f("quality_image", "Изображение качества"), f("global_instance_limit", "Максимум экземпляров", "number"), f("count_player_instances", "Учитывать у игроков", "checkbox"), f("count_market_instances", "Учитывать рынок", "checkbox"), f("count_delivery_instances", "Учитывать доставку", "checkbox"), f("count_container_instances", "Учитывать контейнеры", "checkbox"), f("admin_grant_over_limit", "Выдача сверх лимита", "checkbox"), f("unique_limit_text", "Текст превышения лимита", "emoji_textarea"), f("cursed", "Проклятый", "checkbox"), f("curse_effect_id", "ID проклятья"), f("curse_triggers", "Триггеры проклятья", "list"), f("curse_removable", "Можно снять проклятье", "checkbox"), f("curse_removal_method", "Как снять проклятье"), f("curse_warning_text", "Текст предупреждения", "emoji_textarea"), f("curse_visible", "Показывать проклятье игроку", "checkbox"), f("curse_hidden_until_trigger", "Скрывать до первого срабатывания", "checkbox"), f("ancient", "Древний", "checkbox"), f("ancient_rank", "Древний ранг"), f("ancient_group", "Древняя группа"), f("ancient_description", "Древнее описание", "emoji_textarea"), f("ancient_reveal_requirement", "Условие раскрытия", "json"), f("ancient_upgradable", "Можно улучшать", "checkbox"), f("ancient_cleanable", "Можно очищать", "checkbox"), f("ancient_achievements", "Связанные достижения", "list"), f("ancient_quests", "Связанные квесты", "list")]],
  ["images", "Изображения", [f("main_image", "Основная иконка"), f("item_image", "Изображение предмета"), f("inventory_image", "Изображение для карточки/инвентаря"), f("market_image", "Изображение для рынка"), f("delivery_image", "Изображение для доставки"), f("drop_image", "В сообщении о дропе"), f("profile_image", "В профиле"), f("fallback_image", "Изображение по умолчанию"), f("quality_images", "Изображения по качеству", "json"), f("image_alt", "Альтернативный текст"), f("image_caption", "Подпись")]],
  ["inventory", "Инвентарь", [f("inventory_size", "Занимаемых ячеек", "number"), f("weight", "Вес", "number"), f("inventory_sort_order", "Порядок сортировки", "number"), f("auto_merge_stacks", "Объединять стаки", "checkbox"), f("show_quantity", "Показывать количество", "checkbox"), f("inventory_limit", "Лимит в инвентаре", "number"), f("inventory_full_behavior", "При нехватке места"), f("inventory_full_text", "Текст нехватки места", "emoji_textarea"), f("allow_overflow", "Разрешить временный перегруз", "checkbox"), f("overflow_ttl_seconds", "Время жизни в перегрузе, сек", "number"), f("receive_when_full", "Можно получить при полном инвентаре", "checkbox"), f("store_inventory", "Можно хранить в инвентаре", "checkbox"), f("store_pouch", "Можно хранить в подсумке", "checkbox"), f("store_personal", "Можно хранить в хранилище", "checkbox"), f("store_house", "Можно хранить в доме", "checkbox"), f("store_pavilion", "Можно хранить в павильоне", "checkbox"), f("store_delivery", "Можно отправлять доставкой", "checkbox"), f("store_market", "Можно класть на рынок", "checkbox"), f("can_delete", "Можно удалять", "checkbox"), f("can_drop", "Можно выбрасывать", "checkbox"), f("can_trade", "Можно передавать", "checkbox")]],
  ["economy", "Экономика", [f("priceless", "Бесценный", "checkbox"), f("buy_currency", "Валюта покупки"), f("sell_currency", "Валюта продажи"), f("price_copper", "Цена в медных", "number"), f("price_silver", "Цена в серебряных", "number"), f("price_gold", "Цена в золотых", "number"), f("price_magic_gold", "Цена в магическом золоте", "number"), f("price_ancient_coin", "Цена в древних монетах", "number"), f("price_formula_id", "Формула цены"), f("min_price", "Минимальная цена", "number"), f("max_price", "Максимальная цена", "number"), f("commission_percent", "Комиссия, %", "number"), f("dynamic_price", "Динамическая цена", "checkbox"), f("price_by_quality", "Цена от качества", "checkbox"), f("price_by_durability", "Цена от прочности", "checkbox"), f("buyback_enabled", "Обратный выкуп", "checkbox"), f("buyback_seconds", "Срок выкупа, сек", "number")]],
  ["profile", "Действия в профиле", [f("profile_actions", "Кнопки и действия", "json"), f("profile_action_order", "Порядок кнопок", "list"), f("profile_confirm_actions", "Требуют подтверждения", "list"), f("profile_hidden_actions", "Условия скрытых действий", "json"), f("can_use", "Использовать", "checkbox"), f("can_equip", "Экипировать", "checkbox"), f("can_unequip", "Снять", "checkbox"), f("can_open", "Открыть", "checkbox"), f("can_destroy", "Уничтожить", "checkbox")]],
  ["equipment", "Экипировка", [f("allowed_slots", "Допустимые слоты", "list"), f("weapon_type", "Тип оружия"), f("armor_type", "Тип брони"), f("jewelry_type", "Тип бижутерии"), f("ammo_type", "Тип боеприпаса"), f("required_ammo", "Требует боеприпасы", "checkbox"), f("one_handed", "Одноручный", "checkbox"), f("two_handed", "Двуручный", "checkbox"), f("requires_main_hand", "Требует основную руку", "checkbox"), f("requires_off_hand", "Требует вторую руку", "checkbox"), f("blocks_off_hand", "Блокирует вторую руку", "checkbox"), f("usable_with_shield", "Можно использовать со щитом", "checkbox"), f("usable_with_magic_book", "Можно использовать с магической книгой", "checkbox"), f("usable_with_quiver", "Можно использовать с колчаном", "checkbox"), f("usable_right_hand_injury", "Можно при травме правой руки", "checkbox"), f("usable_left_hand_injury", "Можно при травме левой руки", "checkbox"), f("required_strength", "Требуемая сила", "number"), f("required_agility", "Требуемая ловкость", "number"), f("required_endurance", "Требуемая выносливость", "number"), f("required_intelligence", "Требуемый интеллект", "number"), f("required_wisdom", "Требуемая мудрость", "number"), f("required_perception", "Требуемое восприятие", "number"), f("required_race", "Требуемая раса"), f("required_achievement", "Требуемое достижение"), f("required_reputation", "Требуемая репутация", "json"), f("required_hidden_reputation", "Требуемая скрытая репутация", "json"), f("required_quest", "Требуемый квест"), f("forbidden_equip_effect", "Запрещено при эффекте"), f("required_equip_effect", "Разрешено только при эффекте"), f("set_id", "ID комплекта"), f("set_bonuses", "Бонусы комплекта", "json"), f("bind_on_equip", "Привязка при экипировке", "checkbox"), f("equip_requirements", "Дополнительные требования", "json")]],
  ["stats", "Характеристики", [f("base_damage_min", "Минимальный урон", "number"), f("base_damage_max", "Максимальный урон", "number"), f("damage_type", "Тип урона"), f("attack_speed", "Скорость атаки", "number"), f("attack_range", "Дальность", "number"), f("armor", "Броня", "number"), f("phys_defense", "Физическая защита", "number"), f("magic_defense", "Магическая защита", "number"), f("accuracy", "Точность", "number"), f("evasion", "Уклонение", "number"), f("crit_chance", "Шанс крита", "number"), f("crit_damage", "Критический урон", "number"), f("stat_formulas", "Формулы", "json")]],
  ["effects", "Эффекты", [f("effect_stack_mode", "Сложение эффектов"), f("effect_priority", "Приоритет", "number"), f("effect_immunities", "Иммунитеты", "list"), f("effect_conflicts", "Конфликтующие эффекты", "list"), f("effect_remove_on_unequip", "Снимать при снятии", "checkbox"), f("effect_remove_on_death", "Снимать после смерти", "checkbox"), f("effect_player_texts", "Тексты игроку", "json")]],
  ["usage", "Использование", [f("use_locations", "Где можно использовать", "list"), f("consume_on_use", "Расходуется при использовании", "checkbox"), f("use_trigger", "Триггер"), f("use_cooldown_seconds", "Откат, сек", "number"), f("use_count", "Количество использований", "number"), f("max_uses", "Максимум использований", "number"), f("consume_amount", "Списывать", "number"), f("consume_on_fail", "Списывать при неудаче", "checkbox"), f("use_ends_turn", "Использование завершает ход", "checkbox"), f("use_not_end_turn", "Не завершает ход", "checkbox"), f("use_in_battle", "Можно в бою", "checkbox"), f("use_outside_battle", "Можно вне боя", "checkbox"), f("use_only_city", "Только в городе", "checkbox"), f("use_only_location", "Только в локации", "checkbox"), f("use_only_npc", "Только у NPC", "checkbox"), f("use_only_event", "Только в событии", "checkbox"), f("use_only_quest", "Только при квесте", "checkbox"), f("restore_hp", "Восстановление здоровья", "number"), f("restore_mana", "Восстановление маны", "number"), f("restore_spirit", "Восстановление духа", "number"), f("restore_energy", "Восстановление энергии", "number"), f("regen_hp", "Регенерация здоровья", "number"), f("regen_mana", "Регенерация маны", "number"), f("regen_spirit", "Регенерация духа", "number"), f("temporary_max_hp", "Временный максимум здоровья", "number"), f("temporary_max_mana", "Временный максимум маны", "number"), f("temporary_max_spirit", "Временный максимум духа", "number"), f("temporary_max_energy", "Временный максимум энергии", "number"), f("use_success_chance", "Шанс успеха, %", "number"), f("use_formula_id", "Формула результата"), f("use_results", "Результаты", "json"), f("use_text", "Текст успешного использования", "emoji_textarea"), f("use_error_text", "Текст ошибки", "emoji_textarea"), f("use_wrong_place_text", "Текст неправильного места", "emoji_textarea"), f("use_requirements_text", "Текст нехватки требований", "emoji_textarea"), f("use_cooldown_text", "Текст при откате", "emoji_textarea"), f("use_empty_text", "Текст если предмет закончился", "emoji_textarea"), f("use_battle_forbidden_text", "Текст запрета в бою", "emoji_textarea"), f("use_outside_forbidden_text", "Текст запрета вне боя", "emoji_textarea")]],
  ["container", "Контейнер", [f("can_open", "Можно открыть", "checkbox"), f("open_places", "Где можно открыть", "list"), f("open_requires_key", "Требуется ключ", "checkbox"), f("open_key_id", "ID ключа"), f("open_consumes_key", "Ключ расходуется", "checkbox"), f("consume_on_open", "Предмет исчезает после открытия", "checkbox"), f("replace_on_open", "Заменяется после открытия", "checkbox"), f("replacement_item_id", "ID предмета-замены"), f("remains_on_open", "Остаётся после открытия", "checkbox"), f("becomes_empty", "Становится пустым", "checkbox"), f("show_contents", "Показывать содержимое заранее", "checkbox"), f("check_space_before_open", "Проверять свободное место", "checkbox"), f("open_full_behavior", "Поведение при нехватке места"), f("open_text", "Текст открытия", "emoji_textarea"), f("container_contents", "Содержимое: ID/название/min/max/fixed/chance/quality/group/guarantee/limit/text", "json"), f("guaranteed_rewards", "Гарантированные награды", "json"), f("reward_groups", "Группы наград", "json"), f("pity_enabled", "Гарантия после N открытий", "checkbox"), f("pity_count", "Открытий до гарантии", "number")]],
  ["access", "Доступы", [f("opens_access", "Открывает доступ", "checkbox"), f("access_type", "Тип доступа"), f("access_target", "Цель доступа"), f("access_target_id", "ID цели"), f("access_permanent", "Доступ постоянный", "checkbox"), f("access_temporary", "Доступ временный", "checkbox"), f("access_duration_seconds", "Длительность доступа, сек", "number"), f("access_consumed_on_use", "Предмет расходуется при открытии", "checkbox"), f("access_while_inventory", "Действует пока предмет в инвентаре", "checkbox"), f("access_while_equipped", "Действует пока предмет экипирован", "checkbox"), f("access_lose_on_sale", "Теряется при продаже", "checkbox"), f("access_lose_on_drop", "Теряется при выбрасывании", "checkbox"), f("access_lose_on_transfer", "Теряется при передаче", "checkbox"), f("access_conditions", "Условия доступа", "json")]],
  ["craft", "Ремесло", [f("craft_material", "Можно использовать в ремесле", "checkbox"), f("craft_roles", "Роль ингредиента", "list"), f("craft_types", "Типы ремесла", "list"), f("craft_professions", "Профессии", "list"), f("craft_workshops", "Мастерские", "list"), f("craft_recipes", "Рецепты", "list"), f("craft_consumed", "Расходуется при создании", "checkbox"), f("craft_replaceable", "Можно заменить аналогом", "checkbox"), f("craft_substitute_group", "Группа аналогов"), f("craft_min_quality", "Минимальное качество"), f("craft_quality_influence", "Влияет на качество", "checkbox"), f("craft_success_influence", "Влияет на шанс успеха", "checkbox"), f("craft_effect_influence", "Влияет на дополнительный эффект", "checkbox"), f("craft_result", "Можно создать через ремесло", "checkbox"), f("craft_result_type", "Тип ремесла результата"), f("craft_required_workshop", "Требуемая мастерская"), f("craft_required_recipe", "Требуемый рецепт"), f("craft_required_blueprint", "Требуемый чертёж"), f("craft_result_amount", "Количество результата", "number"), f("craft_result_chance", "Шанс результата", "number"), f("craft_result_quality", "Качество результата"), f("craft_side_result", "Побочный результат", "json"), f("craft_substitutes", "Заменители", "list")]],
  ["modification", "Улучшение / зачарование / разбор", [f("repair_cost_formula_id", "Формула ремонта"), f("can_upgrade", "Можно улучшать", "checkbox"), f("upgrade_type", "Тип улучшения"), f("max_upgrade_level", "Максимальный уровень улучшения", "number"), f("upgrade_materials", "Материалы улучшения", "json"), f("upgrade_cost", "Стоимость улучшения", "number"), f("upgrade_success_chance", "Шанс успеха", "number"), f("upgrade_break_risk", "Риск поломки", "number"), f("upgrade_material_loss_risk", "Риск потери материалов", "number"), f("upgrade_property_chance", "Шанс дополнительного свойства", "number"), f("upgrade_quality_chance", "Шанс усиления качества", "number"), f("upgrade_success_text", "Текст успеха", "emoji_textarea"), f("upgrade_fail_text", "Текст провала", "emoji_textarea"), f("can_enchant", "Можно зачаровать", "checkbox"), f("max_enchants", "Слотов зачарования", "number"), f("allowed_enchant_effects", "Разрешённые эффекты", "list"), f("forbidden_enchant_effects", "Запрещённые эффекты", "list"), f("enchant_materials", "Материалы зачарования", "json"), f("enchant_cost", "Стоимость зачарования", "number"), f("enchant_success_chance", "Шанс успеха зачарования", "number"), f("enchant_curse_risk", "Риск проклятья", "number"), f("enchant_break_risk", "Риск поломки", "number"), f("enchant_cleanable", "Можно очистить зачарование", "checkbox"), f("can_disassemble", "Можно разобрать", "checkbox"), f("disassemble_drops", "Что выпадает", "json"), f("disassemble_min", "Минимальное количество", "number"), f("disassemble_max", "Максимальное количество", "number"), f("disassemble_chance", "Шанс выпадения", "number"), f("disassemble_tool_id", "Требуемый инструмент"), f("disassemble_workshop_id", "Требуемая мастерская"), f("disassemble_cost", "Стоимость разбора", "number"), f("disassemble_success_text", "Текст успеха разбора", "emoji_textarea"), f("disassemble_fail_text", "Текст провала разбора", "emoji_textarea"), f("upgrade_rules", "Дополнительные правила улучшения", "json"), f("enchant_rules", "Дополнительные правила зачарования", "json"), f("disassemble_rules", "Дополнительные правила разбора", "json"), f("destroy_on_upgrade_fail", "Уничтожать при провале", "checkbox")]],
  ["sources", "Дроп и источники", [f("drop_sources", "Источники: тип/ID/название/шанс/вес/min/max/качество/уровень/лимиты/исчерпание/текст", "json"), f("mob_drop_rules", "С мобов", "json"), f("location_drop_rules", "В локациях", "json"), f("event_drop_rules", "В скрытых и обычных событиях", "json"), f("resource_sources", "Из ресурсов", "json"), f("fishing_sources", "Рыбалка", "json"), f("craft_sources", "Ремесло", "json"), f("market_sources", "Обычный/портовый/чёрный рынок", "json"), f("promo_sources", "Промокоды", "list"), f("delivery_sources", "Доставка", "list"), f("quest_sources", "Квесты", "list"), f("achievement_sources", "Достижения", "list"), f("container_sources", "Контейнеры", "list"), f("disassemble_sources", "Разбор", "list"), f("criminal_sources", "Криминальные механики", "list"), f("npc_sources", "NPC", "list"), f("admin_only_source", "Только админ", "checkbox"), f("drop_chance_formula_id", "Формула шанса"), f("weekly_drop_limit", "Недельный лимит", "number")]],
  ["markets", "Рынки", [f("normal_market_allowed", "Доступен на обычном рынке", "checkbox"), f("port_market_allowed", "Доступен на портовом рынке", "checkbox"), f("black_market_allowed", "Доступен на чёрном рынке", "checkbox"), f("npc_market_allowed", "Доступен у NPC-торговца", "checkbox"), f("tavern_market_allowed", "Доступен в таверне", "checkbox"), f("temporary_market_allowed", "Доступен у временного торговца", "checkbox"), f("market_event_only", "Только по событию", "checkbox"), f("market_reputation_only", "Только при репутации", "checkbox"), f("market_hidden_reputation_only", "Только при скрытой репутации", "checkbox"), f("market_buy_price", "Цена покупки на рынке", "number"), f("market_sell_price", "Цена продажи на рынке", "number"), f("market_use_base_price", "Использовать базовую цену", "checkbox"), f("market_use_custom_price", "Использовать индивидуальную цену", "checkbox"), f("market_rules", "Правила конкретных рынков", "json"), f("allowed_markets", "Разрешённые", "list"), f("forbidden_markets", "Запрещённые", "list"), f("market_stock", "Остаток на складе", "number"), f("market_stock_limit", "Максимальный склад", "number"), f("market_restock_seconds", "Время восстановления, сек", "number"), f("market_rotation_group", "Ротационная группа"), f("market_appearance_chance", "Шанс появления", "number"), f("market_buy_conditions", "Условия покупки", "json"), f("market_sell_conditions", "Условия продажи", "json"), f("player_trade_allowed", "Торговля игроков", "checkbox"), f("auction_allowed", "Аукцион", "checkbox")]],
  ["delivery", "Доставка / промокоды / награды", [f("delivery_allowed", "Можно отправлять через доставку", "checkbox"), f("delivery_receive_allowed", "Можно получать через доставку", "checkbox"), f("delivery_delay_seconds", "Задержка доставки, сек", "number"), f("delivery_cost", "Стоимость доставки", "number"), f("delivery_short_message", "Разрешено короткое сообщение", "checkbox"), f("delivery_message_max_length", "Максимальная длина сообщения", "number"), f("delivery_receive_text", "Текст получения", "emoji_textarea"), f("delivery_error_text", "Текст ошибки", "emoji_textarea"), f("delivery_forbid_bound", "Запрет привязанного предмета", "checkbox"), f("delivery_forbid_quest", "Запрет квестового предмета", "checkbox"), f("delivery_time_formula_id", "Формула времени"), f("delivery_cost_formula_id", "Формула стоимости"), f("delivery_risks", "Риски", "json"), f("promo_allowed", "Можно выдавать промокодом", "checkbox"), f("promo_amount", "Количество", "number"), f("promo_quality", "Качество"), f("promo_bind", "Привязывать при получении", "checkbox"), f("promo_player_limit", "Лимит на игрока", "number"), f("promo_global_limit", "Общий лимит", "number"), f("promo_ttl_seconds", "Срок действия, сек", "number"), f("promo_receive_text", "Сообщение при получении", "emoji_textarea"), f("reward_allowed", "Награды", "checkbox"), f("admin_grant_allowed", "Можно выдать админом", "checkbox"), f("admin_grant_forbidden", "Запрещено выдавать админом", "checkbox"), f("admin_grant_reason_required", "Требуется причина", "checkbox"), f("admin_grant_log", "Логировать выдачу", "checkbox"), f("admin_grant_text", "Сообщение игроку", "emoji_textarea"), f("grant_limits", "Лимиты", "json"), f("delivery_texts", "Дополнительные тексты", "json")]],
  ["restrictions", "Условия и ограничения", [f("max_player_level", "Максимальный уровень", "number"), f("allowed_races", "Разрешённые расы", "list"), f("forbidden_races", "Запрещённые расы", "list"), f("required_achievements", "Достижения", "list"), f("required_reputation", "Репутация", "json"), f("required_hidden_reputation", "Скрытая репутация", "json"), f("required_quests", "Квесты", "list"), f("required_locations", "Локации", "list"), f("required_cities", "Города", "list"), f("required_events", "События", "list"), f("required_seasons", "Сезоны", "list"), f("time_windows", "Время суток", "json"), f("required_effects", "Наличие эффектов", "list"), f("forbidden_effects", "Отсутствие/запрещающие эффекты", "list"), f("required_fines", "Наличие штрафов", "list"), f("forbidden_fines", "Отсутствие штрафов", "list"), f("required_items", "Наличие других предметов", "list"), f("forbidden_items", "Отсутствие других предметов", "list"), f("bind_on_receive", "Привязывается при получении", "checkbox"), f("bind_on_equip", "Привязывается при экипировке", "checkbox"), f("bind_on_use", "Привязывается при использовании", "checkbox"), f("bound_no_transfer", "Нельзя передать", "checkbox"), f("bound_no_sell", "Нельзя продать", "checkbox"), f("bound_no_drop", "Нельзя выбросить", "checkbox"), f("bound_no_disassemble", "Нельзя разобрать", "checkbox"), f("bound_no_upgrade", "Нельзя улучшить", "checkbox"), f("bound_no_enchant", "Нельзя зачаровать", "checkbox"), f("bound_keep_on_death", "Нельзя потерять при смерти", "checkbox"), f("platform_restrictions", "Telegram/VK/web", "json")]],
  ["relations", "Связи", [f("related_items", "Связанные предметы", "list"), f("replacement_items", "Замены", "list"), f("required_items", "Требуемые", "list"), f("incompatible_items", "Несовместимые", "list"), f("related_effects", "Эффекты", "list"), f("related_formulas", "Формулы", "list"), f("related_quests", "Квесты", "list"), f("related_achievements", "Достижения", "list"), f("relation_notes", "Пояснение", "textarea")]],
  ["publication", "Публикация и история", [f("publication_notes", "Комментарий к публикации", "textarea"), f("change_summary", "Описание изменений", "textarea"), f("test_scenarios", "Сценарии проверки", "json"), f("telegram_preview_text", "Контрольный текст Telegram", "emoji_textarea"), f("vk_preview_text", "Контрольный текст VK", "emoji_textarea"), f("migration_notes", "Примечания миграции", "textarea"), f("deprecated", "Устаревший", "checkbox"), f("deprecation_replacement_id", "ID замены")]],
];

function JsonEditor({ value, onChange, disabled }) {
  const [text, setText] = useState("");
  const [error, setError] = useState("");
  useEffect(() => setText(JSON.stringify(value ?? [], null, 2)), [value]);
  const commit = () => { try { onChange(JSON.parse(text || "[]")); setError(""); } catch { setError("Некорректный JSON — изменение не сохранено."); } };
  return <><textarea className="ntv2-mono" rows={5} value={text} disabled={disabled} onChange={(e) => setText(e.target.value)} onBlur={commit} />{error ? <span className="ntv2-error">{error}</span> : null}</>;
}

export function ItemTzFields({ value, onChange, disabled, formulaOptions = [] }) {
  const [active, setActive] = useState("main");
  const tab = TABS.find(([id]) => id === active) || TABS[0];
  const set = (key, next) => onChange({ ...value, [key]: next });
  return <div className="ntv2-panel">
    <h3>Полная карточка предмета по ТЗ 2.0</h3>
    <div className="ntv2-subnav" role="tablist">{TABS.map(([id, label], i) => <button type="button" role="tab" aria-selected={id === active} className={`ntv2-subnav-item${id === active ? " active" : ""}`} key={id} onClick={() => setActive(id)}>{i + 1}. {label}</button>)}</div>
    <div className="ntv2-world-form" role="tabpanel">{tab[2].map((field) => {
      const current = value[field.key];
      if (field.type === "checkbox") return <label className="ntv2-check" key={field.key}><input type="checkbox" checked={Boolean(current)} disabled={disabled} onChange={(e) => set(field.key, e.target.checked)} /> {field.label}</label>;
      if (field.type === "emoji") return <label className="ntv2-field" key={field.key}><span>{field.label}</span><EmojiInput value={current || ""} disabled={disabled} onChange={(next) => set(field.key, next)} /></label>;
      if (field.type === "emoji_textarea") return <label className="ntv2-field" key={field.key}><span>{field.label}</span><EmojiTextarea rows={3} value={current || ""} disabled={disabled} onChange={(next) => set(field.key, next)} /></label>;
      if (field.type === "textarea") return <label className="ntv2-field" key={field.key}><span>{field.label}</span><textarea rows={3} value={current || ""} disabled={disabled} onChange={(e) => set(field.key, e.target.value)} /></label>;
      if (field.type === "list") return <label className="ntv2-field" key={field.key}><span>{field.label}</span><textarea rows={3} value={(Array.isArray(current) ? current : []).join("\n")} disabled={disabled} onChange={(e) => set(field.key, e.target.value.split("\n").map((x) => x.trim()).filter(Boolean))} /></label>;
      if (field.type === "json") return <label className="ntv2-field" key={field.key}><span>{field.label}</span><JsonEditor value={current} disabled={disabled} onChange={(next) => set(field.key, next)} /></label>;
      if (field.key.endsWith("_formula_id")) return <label className="ntv2-field" key={field.key}><span>{field.label}</span><select value={current || ""} disabled={disabled} onChange={(e) => set(field.key, e.target.value)}><option value="">— без формулы —</option>{formulaOptions.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;
      return <label className="ntv2-field" key={field.key}><span>{field.label}</span><input type={field.type === "number" ? "number" : "text"} value={current ?? ""} disabled={disabled} onChange={(e) => set(field.key, e.target.value)} /></label>;
    })}</div>
  </div>;
}
