export const profileMockData = {
  assets: {
    background: "/assets/profile/backgrounds/1.png",
    raceModels: {
      human: "/assets/profile/models/human.png",
      elf: "/assets/profile/models/elf.png",
      dwarf: "/assets/profile/models/dwarf.png",
      undead: "/assets/profile/models/undead.png",
      lizardfolk: "/assets/profile/models/lizardfolk.png",
    },
  },
  player: {
    userGlobalId: "NT-DEMO",
    publicId: "demo",
    nickname: "Путник Селдара",
    raceKey: "human",
    raceName: "Человек",
    branch: "Ветвь не выбрана",
    level: 12,
    experienceCurrent: 560,
    experienceToNext: 1200,
    freeAttributePoints: 5,
    freeSkillPoints: 2,
    balanceText: "2 зол. 450 сер.",
    registrationDate: "12.05.2026",
  },
  attributes: [
    { key: "strength", label: "Сила", value: 8, description: "Физический урон, пробой, блоки." },
    { key: "endurance", label: "Выносливость", value: 9, description: "HP, защита, дух." },
    { key: "agility", label: "Ловкость", value: 7, description: "Уклонение, парирование, быстрые атаки." },
    { key: "perception", label: "Восприятие", value: 8, description: "Точность, крит, обнаружение угроз." },
    { key: "intelligence", label: "Интеллект", value: 6, description: "Мана и сложные формы." },
    { key: "wisdom", label: "Мудрость", value: 6, description: "Концентрация, поддержка, лечение." },
  ],
  parameters: [
    { label: "HP", value: "156 / 156" },
    { label: "Дух", value: "62 / 62" },
    { label: "Мана", value: "48 / 48" },
    { label: "Энергия", value: "100 / 100" },
    { label: "Концентрация", value: "4 / 4" },
    { label: "Физическая защита", value: 18 },
    { label: "Магическая защита", value: 12 },
    { label: "Точность", value: 22 },
    { label: "Уклонение", value: 20 },
    { label: "Шанс крита", value: "3%" },
  ],
  effects: [],
  activeSets: [{ name: "Полевой комплект", bonus: "+2 к выносливости при 2 предметах." }],
  equipmentSlots: [
    { key: "helmet", label: "Шлем" },
    { key: "necklace", label: "Ожерелье" },
    { key: "chest", label: "Нагрудник" },
    { key: "belt", label: "Пояс" },
    { key: "pants", label: "Штаны" },
    { key: "boots", label: "Ботинки" },
    { key: "gloves", label: "Перчатки" },
    { key: "ring1", label: "Кольцо 1" },
    { key: "ring2", label: "Кольцо 2" },
    { key: "weapon1", label: "Оружие 1" },
    { key: "weapon2", label: "Оружие 2" },
    { key: "special", label: "Особый слот" },
  ],
  equipment: {
    weapon1: {
      id: "demo_sword",
      name: "Простой меч",
      category: "Оружие",
      type: "Меч",
      quality: "обычный",
      level: 10,
      description: "Надёжный клинок для первых вылазок за стены Селдара.",
      stats: ["+3 к урону"],
      actions: ["Снять"],
    },
  },
  inventory: [
    {
      id: "demo_potion",
      name: "Малое зелье энергии",
      category: "Алхимия",
      type: "Зелье",
      quality: "обычный",
      level: 1,
      amount: 3,
      description: "Восстанавливает немного энергии.",
      stats: ["+15 энергии"],
      actions: ["Использовать"],
    },
    {
      id: "demo_ring",
      name: "Кольцо Тихого Прилива",
      category: "Бижутерия",
      type: "Кольцо",
      quality: "эпический",
      level: 12,
      amount: 1,
      targetSlotKey: "ring1",
      description: "Кольцо с мягким синим отблеском.",
      stats: ["+2 мудрость", "+1 восприятие"],
      enchantments: ["Усиление концентрации"],
      actions: ["Надеть"],
    },
  ],
  skills: {
    active: [{ name: "Обычная атака", level: 1, description: "Базовый удар оружием." }],
    passive: [{ name: "Меткий взгляд", level: 2, description: "+точность через восприятие." }],
  },
  information: {
    achievements: [{ name: "Первый шаг", description: "Персонаж создан." }],
    rating: { globalPlace: "—", pvePlace: "—", pvpPlace: "—", craftPlace: "—" },
    activity: {
      pveKills: 0,
      pvpKills: 0,
      soulParticlesAbsorbed: 0,
      craftingLevels: [
        { name: "Кузнечное дело", level: 1, exp: "0 опыта" },
        { name: "Алхимия", level: 1, exp: "0 опыта" },
      ],
    },
  },
};
