"""Starter equipment for new Ner-Talis characters."""

from __future__ import annotations

from copy import deepcopy
from typing import Any

STARTER_EQUIPMENT_SLOTS = ["weapon1", "chest", "pants", "boots", "helmet"]

STARTER_ITEMS: list[dict[str, Any]] = [
    {
        "id": "starter_wooden_staff",
        "name": "Деревянный посох",
        "icon": "/assets/items/starter/wooden_staff.png",
        "type": "Оружие",
        "slot": "weapon1",
        "subtype": "Посох",
        "quality": "обычный",
        "special_type": None,
        "state": "обычное",
        "item_level": 1,
        "starter_item": True,
        "bound_on_receive": True,
        "requirements": {"level": 1},
        "combat": {
            "damage_type": "Дробящий физический",
            "damage_min": 4,
            "damage_max": 7,
            "attack_speed": "Обычная",
            "range": "Ближний бой",
            "two_handed": True,
        },
        "stats": ["Мана: +2"],
        "properties": [],
        "gem_slots": 0,
        "enchant_slots": 0,
        "can_enchant": False,
        "can_insert_gems": False,
        "set": None,
        "scalable": False,
        "curse": None,
        "can_upgrade": True,
        "can_trade": False,
        "can_sell": True,
        "sell_price_copper": 20,
        "description": "Простой посох из неровной древесины. Слабое стартовое оружие, подходящее для первых боёв и обучения.",
        "asset_icon": "/assets/items/starter/wooden_staff.png",
        "slotKey": "weapon1",
        "targetSlotKey": "weapon1",
        "level": 1,
        "category": "Оружие",
        "stat_modifiers": {
            "armor": 0,
            "magic_armor": 0,
            "bonus_hp": 0,
            "bonus_spirit": 0,
            "bonus_mana": 2,
            "bonus_accuracy": 1,
            "bonus_dodge": 0,
            "bonus_strength": 0,
            "bonus_endurance": 0,
            "bonus_agility": 0,
            "bonus_perception": 0,
            "bonus_intelligence": 0,
            "bonus_wisdom": 0,
        },
        "actions": ["Снять"],
        "amount": 1,
    },
    {
        "id": "starter_tunic",
        "name": "Туника",
        "icon": "/assets/items/starter/tunic.png",
        "type": "Броня",
        "slot": "chest",
        "subtype": "Тканевая броня",
        "quality": "обычный",
        "special_type": None,
        "state": "обычное",
        "item_level": 1,
        "starter_item": True,
        "bound_on_receive": True,
        "requirements": {"level": 1},
        "combat": {},
        "stats": ["Броня: +2"],
        "properties": [],
        "gem_slots": 0,
        "enchant_slots": 0,
        "can_enchant": False,
        "can_insert_gems": False,
        "set": None,
        "scalable": False,
        "curse": None,
        "can_upgrade": True,
        "can_trade": False,
        "can_sell": True,
        "sell_price_copper": 20,
        "description": "Грубая, но целая туника. Даёт минимальную защиту тела и немного повышает выживаемость новичка.",
        "asset_icon": "/assets/items/starter/tunic.png",
        "slotKey": "chest",
        "targetSlotKey": "chest",
        "level": 1,
        "category": "Снаряжение",
        "stat_modifiers": {
            "armor": 2,
            "magic_armor": 1,
            "bonus_hp": 5,
            "bonus_spirit": 0,
            "bonus_mana": 0,
            "bonus_accuracy": 0,
            "bonus_dodge": 0,
            "bonus_strength": 0,
            "bonus_endurance": 0,
            "bonus_agility": 0,
            "bonus_perception": 0,
            "bonus_intelligence": 0,
            "bonus_wisdom": 0,
        },
        "actions": ["Снять"],
        "amount": 1,
    },
    {
        "id": "starter_canvas_pants",
        "name": "Холщевые штаны",
        "icon": "/assets/items/starter/canvas_pants.png",
        "type": "Броня",
        "slot": "pants",
        "subtype": "Тканевая броня",
        "quality": "обычный",
        "special_type": None,
        "state": "обычное",
        "item_level": 1,
        "starter_item": True,
        "bound_on_receive": True,
        "requirements": {"level": 1},
        "combat": {},
        "stats": ["Дух: +1"],
        "properties": [],
        "gem_slots": 0,
        "enchant_slots": 0,
        "can_enchant": False,
        "can_insert_gems": False,
        "set": None,
        "scalable": False,
        "curse": None,
        "can_upgrade": True,
        "can_trade": False,
        "can_sell": True,
        "sell_price_copper": 20,
        "description": "Простые холщевые штаны. Почти не защищают, но не сковывают движение.",
        "asset_icon": "/assets/items/starter/canvas_pants.png",
        "slotKey": "pants",
        "targetSlotKey": "pants",
        "level": 1,
        "category": "Снаряжение",
        "stat_modifiers": {
            "armor": 1,
            "magic_armor": 0,
            "bonus_hp": 0,
            "bonus_spirit": 1,
            "bonus_mana": 0,
            "bonus_accuracy": 0,
            "bonus_dodge": 1,
            "bonus_strength": 0,
            "bonus_endurance": 0,
            "bonus_agility": 0,
            "bonus_perception": 0,
            "bonus_intelligence": 0,
            "bonus_wisdom": 0,
        },
        "actions": ["Снять"],
        "amount": 1,
    },
    {
        "id": "starter_old_boots",
        "name": "Старые сапоги",
        "icon": "/assets/items/starter/old_boots.png",
        "type": "Броня",
        "slot": "boots",
        "subtype": "Лёгкие сапоги",
        "quality": "обычный",
        "special_type": None,
        "state": "изношенное",
        "item_level": 1,
        "starter_item": True,
        "bound_on_receive": True,
        "requirements": {"level": 1},
        "combat": {},
        "stats": ["Уклонение: +2"],
        "properties": [],
        "gem_slots": 0,
        "enchant_slots": 0,
        "can_enchant": False,
        "can_insert_gems": False,
        "set": None,
        "scalable": False,
        "curse": None,
        "can_upgrade": True,
        "can_trade": False,
        "can_sell": True,
        "sell_price_copper": 20,
        "description": "Потрёпанные сапоги с мягкой подошвой. Защищают ноги и немного помогают уклоняться.",
        "asset_icon": "/assets/items/starter/old_boots.png",
        "slotKey": "boots",
        "targetSlotKey": "boots",
        "level": 1,
        "category": "Снаряжение",
        "stat_modifiers": {
            "armor": 1,
            "magic_armor": 0,
            "bonus_hp": 0,
            "bonus_spirit": 0,
            "bonus_mana": 0,
            "bonus_accuracy": 0,
            "bonus_dodge": 2,
            "bonus_strength": 0,
            "bonus_endurance": 0,
            "bonus_agility": 0,
            "bonus_perception": 0,
            "bonus_intelligence": 0,
            "bonus_wisdom": 0,
        },
        "actions": ["Снять"],
        "amount": 1,
    },
    {
        "id": "starter_bandana",
        "name": "Бандана",
        "icon": "/assets/items/starter/bandana.png",
        "type": "Броня",
        "slot": "helmet",
        "subtype": "Тканевый головной убор",
        "quality": "обычный",
        "special_type": None,
        "state": "обычное",
        "item_level": 1,
        "starter_item": True,
        "bound_on_receive": True,
        "requirements": {"level": 1},
        "combat": {},
        "stats": ["Точность: +1"],
        "properties": [],
        "gem_slots": 0,
        "enchant_slots": 0,
        "can_enchant": False,
        "can_insert_gems": False,
        "set": None,
        "scalable": False,
        "curse": None,
        "can_upgrade": True,
        "can_trade": False,
        "can_sell": True,
        "sell_price_copper": 20,
        "description": "Обычная тканевая бандана. Почти не защищает, но не мешает обзору и помогает внимательнее целиться.",
        "asset_icon": "/assets/items/starter/bandana.png",
        "slotKey": "helmet",
        "targetSlotKey": "helmet",
        "level": 1,
        "category": "Снаряжение",
        "stat_modifiers": {
            "armor": 1,
            "magic_armor": 0,
            "bonus_hp": 0,
            "bonus_spirit": 0,
            "bonus_mana": 0,
            "bonus_accuracy": 1,
            "bonus_dodge": 0,
            "bonus_strength": 0,
            "bonus_endurance": 0,
            "bonus_agility": 0,
            "bonus_perception": 1,
            "bonus_intelligence": 0,
            "bonus_wisdom": 0,
        },
        "actions": ["Снять"],
        "amount": 1,
    },
]


def get_starter_equipment() -> dict[str, dict[str, Any]]:
    """Return starter items keyed by profile equipment slot."""
    return {item["slotKey"]: deepcopy(item) for item in STARTER_ITEMS}


def get_starter_inventory() -> list[dict[str, Any]]:
    """Return starter items as inventory items, if a flow wants unequipped start."""
    inventory: list[dict[str, Any]] = []
    for item in STARTER_ITEMS:
        clone = deepcopy(item)
        clone["targetSlotKey"] = clone.get("slotKey")
        clone.pop("slotKey", None)
        clone["actions"] = ["Надеть"]
        inventory.append(clone)
    return inventory
