"""Helpers for short-lived website links generated by bots."""

from __future__ import annotations

import os
from typing import Any

PROFILE_SCOPE = "profile"
PAVILION_SCOPE = "pavilion"
DEFAULT_SESSION_TTL_MINUTES = 15


def get_web_session_ttl_minutes() -> int:
    raw_value = os.getenv("WEB_SESSION_TTL_MINUTES", str(DEFAULT_SESSION_TTL_MINUTES)).strip()
    try:
        value = int(raw_value)
    except ValueError:
        value = DEFAULT_SESSION_TTL_MINUTES
    return max(1, min(value, 120))


def get_site_base_url() -> str:
    """Return the public website base URL without a trailing slash."""
    base_url = os.getenv("SITE_BASE_URL", "").strip()
    if not base_url:
        profile_url = os.getenv("SITE_PROFILE_BASE_URL", "https://example.com/profile").strip()
        if profile_url.endswith("/profile"):
            base_url = profile_url[: -len("/profile")]
        else:
            base_url = profile_url
    return base_url.rstrip("/") or "https://example.com"


def build_site_url(path: str, token: str) -> str:
    cleaned_path = "/" + path.strip("/")
    return f"{get_site_base_url()}{cleaned_path}?token={token}"


def build_profile_site_url(token: str) -> str:
    return build_site_url("/profile", token)


def build_pavilion_site_url(token: str) -> str:
    custom_url = os.getenv("SITE_PAVILION_URL", "").strip()
    if custom_url:
        return f"{custom_url.rstrip('/')}?token={token}"
    return build_site_url("/pavilion", token)


def create_web_session_token(storage: Any, game_id: str, scope: str, platform: str) -> str:
    ttl = get_web_session_ttl_minutes()
    try:
        return storage.create_web_session(
            game_id=game_id,
            scope=scope,
            platform=platform,
            lifetime_minutes=ttl,
        )
    except TypeError:
        return storage.create_web_session(
            game_id=game_id,
            scope=scope,
            platform=platform,
            ttl_minutes=ttl,
        )


def create_profile_site_link(storage: Any, player: dict[str, Any], platform: str) -> str:
    token = create_web_session_token(storage, player["game_id"], PROFILE_SCOPE, platform)
    return build_profile_site_url(token)


def create_pavilion_site_link(storage: Any, player: dict[str, Any], platform: str) -> str:
    token = create_web_session_token(storage, player["game_id"], PAVILION_SCOPE, platform)
    return build_pavilion_site_url(token)
